import { useEffect, useState } from 'react';
import { authApi } from '../../infrastructure/api/auth';
import { exportLocalBackup, parseBackup, restoreLocalBackup } from '../../infrastructure/backup.service';
import { useAuthStore } from '../../state/authStore';
import { db } from '../../db/database';

export function AccountPage(){
  const user=useAuthStore(s=>s.user); const logout=useAuthStore(s=>s.logout);
  const [data,setData]=useState<any>(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [showCurrent,setShowCurrent]=useState(false);const [showNext,setShowNext]=useState(false);
  const [deletePassword,setDeletePassword]=useState('');const [deleteOpen,setDeleteOpen]=useState(false);
  const [sessions,setSessions]=useState<any[]>([]); const [restoreBusy,setRestoreBusy]=useState(false);
  useEffect(()=>{void Promise.all([authApi.account(),authApi.sessions()]).then(([a,s])=>{setData(a);setSessions(s.sessions)}).catch(e=>setError(e instanceof Error?e.message:'Không thể tải tài khoản'))},[]);
  async function changePassword(){setBusy(true);setError('');try{await authApi.changePassword(current,next,confirm);setCurrent('');setNext('');setConfirm('');alert('Đổi mật khẩu thành công. Các phiên đăng nhập khác đã bị đăng xuất.')}catch(e){setError(e instanceof Error?e.message:'Không thể đổi mật khẩu')}finally{setBusy(false)}}
  async function backup(format:'json'|'zip'){const blob=await exportLocalBackup(format);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`thi-thu-backup-${new Date().toISOString().slice(0,10)}.${format}`;a.click();URL.revokeObjectURL(a.href)}
  async function restore(file:File){try{const preview=await parseBackup(file);const counts=Object.entries(preview.tables).filter(([,v])=>Array.isArray(v)&&v.length).map(([k,v])=>`${k}: ${(v as unknown[]).length}`).join('\n');const conflicts=Object.values(preview.conflicts).reduce((a,b)=>a+b,0);if(!window.confirm(`Backup version ${preview.version}\n${counts}\n\n${conflicts?`Có ${conflicts} bản ghi trùng ID; các bản ghi trùng sẽ được bỏ qua.`:'Không có ID trùng.'}\n\nImport?`))return}catch(e){setError(e instanceof Error?e.message:'Backup không hợp lệ');return}setRestoreBusy(true);try{await restoreLocalBackup(file,'merge');alert('Khôi phục backup thành công.')}catch(e){setError(e instanceof Error?e.message:'Backup không hợp lệ')}finally{setRestoreBusy(false)}}
  async function deleteAccount(){setBusy(true);try{await authApi.deleteAccount(deletePassword);await db.syncQueue.clear();await db.syncState.clear();await logout();window.location.assign('/login')}catch(e){setError(e instanceof Error?e.message:'Không thể xóa tài khoản')}finally{setBusy(false)}}
  return <div className="page-stack max-w-4xl mx-auto"><section className="page-hero"><div><span className="eyebrow">TÀI KHOẢN</span><h1>Quản lý tài khoản</h1><p>Thông tin tài khoản server và dữ liệu offline trên thiết bị.</p></div></section>{error&&<p className="form-error">{error}</p>}
    <section className="card"><h2 className="font-bold text-lg">Thông tin</h2><div className="grid sm:grid-cols-2 gap-3 mt-4 text-sm"><Info label="Tên" value={user?.name}/><Info label="Username" value={user?.username}/><Info label="Ngày đăng ký" value={user?.createdAt?new Date(user.createdAt).toLocaleString('vi-VN'):''}/><Info label="Lần đăng nhập cuối" value={user?.lastLoginAt?new Date(user.lastLoginAt).toLocaleString('vi-VN'):'Chưa có'}/></div></section>
    <section className="stat-grid"><Stat label="Tổng bài làm" value={data?.stats?.total}/><Stat label="Thi đấu" value={data?.stats?.tournament}/><Stat label="Luyện tập" value={data?.stats?.practice}/><Stat label="English" value={data?.stats?.english}/><Stat label="Đề tạo" value={data?.stats?.exams}/><Stat label="Share" value={data?.stats?.shares}/></section>
    <section className="card"><h2 className="font-bold text-lg">Đổi mật khẩu</h2><div className="space-y-3 mt-4"><PasswordInput label="Mật khẩu hiện tại" value={current} setValue={setCurrent} show={showCurrent} setShow={setShowCurrent}/><PasswordInput label="Mật khẩu mới" value={next} setValue={setNext} show={showNext} setShow={setShowNext}/><input className="input" type="password" placeholder="Xác nhận mật khẩu mới" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="btn-primary" disabled={busy||!current||next.length<10||next!==confirm} onClick={()=>void changePassword()}>{busy?'Đang xử lý…':'Đổi mật khẩu'}</button></div></section>
    <section className="card"><div className="flex justify-between items-center"><div><h2 className="font-bold text-lg">Phiên đăng nhập</h2><p className="text-sm text-slate-500 mt-1">Không hiển thị session secret. Chỉ hiển thị metadata cần thiết.</p></div><button className="btn-secondary" onClick={()=>void authApi.revokeOtherSessions().then(()=>authApi.sessions()).then(r=>setSessions(r.sessions))}>Đăng xuất thiết bị khác</button></div><div className="space-y-2 mt-4">{sessions.map(s=><div key={s.id} className="border rounded-xl p-3 text-sm"><div className="flex justify-between"><b>{s.current?'Thiết bị hiện tại':'Thiết bị khác'}</b><span>{new Date(s.lastSeenAt).toLocaleString('vi-VN')}</span></div><p className="text-slate-500 mt-1">{s.userAgent||'Không xác định'}</p></div>)}</div></section>
    <section className="card"><h2 className="font-bold text-lg">Backup / Restore</h2><p className="text-sm text-slate-500 mt-1">Export local exams, attempts, vocabulary, settings và dữ liệu học tập thành JSON. Sync queue không được export để tránh replay mutation cũ.</p><div className="flex gap-2 mt-4"><button className="btn-secondary" onClick={()=>void backup('json')}>Export backup JSON</button><button className="btn-secondary" onClick={()=>void backup('zip')}>Export backup ZIP</button><label className="btn-secondary cursor-pointer">{restoreBusy?'Đang import…':'Import backup JSON'}<input className="hidden" type="file" accept="application/json,.json,application/zip,.zip" disabled={restoreBusy} onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f)}}/></label></div></section>
    <section className="card border-red-200"><h2 className="font-bold text-lg text-red-700">Xóa tài khoản</h2><p className="text-sm text-slate-500 mt-1">Tài khoản sẽ chuyển sang DELETED, session bị revoke và không thể đăng nhập lại. Security/audit records cần thiết có thể được giữ lại.</p><button className="btn-primary !bg-red-600 mt-4" onClick={()=>setDeleteOpen(true)}>Xóa tài khoản</button></section>
    {deleteOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="card max-w-md w-full p-6"><h2 className="text-lg font-bold">Xóa tài khoản?</h2><p className="text-sm text-slate-500 mt-2">Hành động này không thể hoàn tác. Nhập mật khẩu hiện tại và chữ DELETE để xác nhận.</p><input className="input mt-4" type="password" placeholder="Mật khẩu hiện tại" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/><div className="flex justify-end gap-2 mt-4"><button className="btn-secondary" disabled={busy} onClick={()=>setDeleteOpen(false)}>Hủy</button><button className="btn-primary !bg-red-600" disabled={busy||!deletePassword} onClick={()=>void deleteAccount()}>Xóa vĩnh viễn</button></div></div></div>}
  </div>
}
function Info({label,value}:{label:string;value?:string}){return <div className="rounded-xl bg-slate-50 p-3"><span className="block text-xs text-slate-400">{label}</span><b className="block mt-1 break-all">{value||'—'}</b></div>}
function Stat({label,value}:{label:string;value:any}){return <div className="stat-card"><div><strong>{value??'—'}</strong><span>{label}</span></div></div>}
function PasswordInput({label,value,setValue,show,setShow}:{label:string;value:string;setValue:(v:string)=>void;show:boolean;setShow:(v:boolean)=>void}){return <div className="relative"><input className="input pr-12" type={show?'text':'password'} placeholder={label} value={value} onChange={e=>setValue(e.target.value)} autoComplete="current-password"/><button type="button" className="absolute right-2 top-1/2 -translate-y-1/2 text-sm" aria-label={show?'Ẩn mật khẩu':'Hiện mật khẩu'} onClick={()=>setShow(!show)}>👁</button></div>}
