import { useEffect,useState } from 'react';
import { adminApi } from '../../infrastructure/api/auth';
export function AdminAiPage(){
 const [data,setData]=useState<any>();const [limits,setLimits]=useState({chatPerMinute:20,explainPerMinute:10,jsonPerMinute:5});const [name,setName]=useState('');const [key,setKey]=useState('');const [model,setModel]=useState('llama-3.3-70b-versatile');const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false);
 const load=()=>{void Promise.all([adminApi.aiKeys(),adminApi.aiSettings()]).then(([keys,settings])=>{setData(keys);if(settings?.limits)setLimits(settings.limits)}).catch(e=>setMsg(e.message))};useEffect(load,[]);
 async function add(){if(!name||!key)return;try{await adminApi.addAiKey(name,key,model);setName('');setKey('');setMsg('Đã thêm API key và lưu vào SQLite.');load()}catch(e){setMsg(e instanceof Error?e.message:'Không thể thêm')}}
 async function saveLimits(){setSaving(true);setMsg('');try{const clean={chatPerMinute:Math.max(0,Math.floor(limits.chatPerMinute)),explainPerMinute:Math.max(0,Math.floor(limits.explainPerMinute)),jsonPerMinute:Math.max(0,Math.floor(limits.jsonPerMinute))};const r=await adminApi.setAiSettings(clean);setLimits(r.limits);setMsg('Đã lưu giới hạn AI. Áp dụng cho từng tài khoản theo phút.')}catch(e){setMsg(e instanceof Error?e.message:'Không thể lưu')}finally{setSaving(false)}}
 return <div className="space-y-5"><div className="admin-page-heading"><div><span className="admin-eyebrow">AI & GROQ</span><h1>Quản lý AI</h1><p>API key và giới hạn sử dụng được lưu server-side, không phụ thuộc frontend.</p></div></div>
 <section className="card space-y-3"><div><h2 className="font-semibold">Giới hạn sử dụng AI</h2><p className="text-sm text-slate-500">Số lượt tối đa mỗi phút cho <b>mỗi tài khoản</b>. Đặt 0 để khóa loại AI đó.</p></div><div className="grid md:grid-cols-3 gap-3"><label className="text-sm">AI chat<input className="input mt-1" type="number" min="0" max="1000" value={limits.chatPerMinute} onChange={e=>setLimits({...limits,chatPerMinute:Number(e.target.value)})}/></label><label className="text-sm">Giải thích câu hỏi<input className="input mt-1" type="number" min="0" max="1000" value={limits.explainPerMinute} onChange={e=>setLimits({...limits,explainPerMinute:Number(e.target.value)})}/></label><label className="text-sm">Sửa JSON<input className="input mt-1" type="number" min="0" max="1000" value={limits.jsonPerMinute} onChange={e=>setLimits({...limits,jsonPerMinute:Number(e.target.value)})}/></label></div><button className="btn-primary" disabled={saving} onClick={()=>void saveLimits()}>{saving?'Đang lưu…':'Lưu giới hạn'}</button></section>
 <section className="card space-y-3"><h2 className="font-semibold">Thêm Groq API</h2><div className="grid md:grid-cols-3 gap-3"><input className="input" placeholder="Tên key" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="gsk_..." type="password" value={key} onChange={e=>setKey(e.target.value)}/><input className="input" placeholder="Model" value={model} onChange={e=>setModel(e.target.value)}/></div><button className="btn-primary" onClick={()=>void add()}>Thêm API key</button>{msg&&<p className="text-sm text-slate-500">{msg}</p>}</section>
 <section className="card"><h2 className="font-semibold mb-3">Pool API hiện tại</h2><div className="space-y-2">{(data?.keys??[]).map((k:any)=><div key={k.id} className="flex items-center justify-between gap-3 border rounded-xl p-3"><div><strong>{k.name}</strong><p className="text-xs text-slate-500">{k.maskedKey} · {k.model} · lỗi {k.failures}</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>void adminApi.setAiKey(k.id,!k.enabled).then(load)}>{k.enabled?'Tắt':'Bật'}</button>{k.id!=='env-default'&&<button className="btn-secondary text-red-600" onClick={()=>void adminApi.deleteAiKey(k.id).then(load)}>Xóa</button>}</div></div>)}{!(data?.keys?.length)&&<p className="text-sm text-slate-500">Chưa có Groq API. Hãy thêm key hoặc đặt GROQ_API_KEY trên Railway.</p>}</div></section>
 </div>
}
