import { useEffect,useState } from 'react';import { Link } from 'react-router-dom';import { adminApi, type AdminExamRow, type OfficialExamRow } from '../../infrastructure/api/auth';import { importExam } from '@exam/exam-format';import { Skeleton } from '../components/Skeleton';
export function AdminExamsPage(){const [tab,setTab]=useState<'official'|'user'>('official');
 return <div className="page-stack max-w-7xl mx-auto"><section className="page-hero"><div><span className="eyebrow">ADMIN</span><h1>Quản lý đề</h1><p>Đề chính thức (public cho mọi người) và đề do người dùng tạo (nội dung vi phạm có thể bị gỡ).</p></div></section>
 <div className="flex flex-wrap gap-2"><button className={`btn-secondary ${tab==='official'?'!border-[var(--accent)]':''}`} onClick={()=>setTab('official')}>Đề chính thức</button><button className={`btn-secondary ${tab==='user'?'!border-[var(--accent)]':''}`} onClick={()=>setTab('user')}>Đề của người dùng</button></div>
 {tab==='official'?<OfficialExams/>:<UserExams/>}</div>;}

function OfficialExams(){const [rows,setRows]=useState<OfficialExamRow[]>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const load=()=>adminApi.officialList().then(r=>setRows(r.exams)).catch(e=>setError(e instanceof Error?e.message:'Không thể tải đề'));useEffect(()=>{void load()},[]);
 async function upload(file:File){setBusy(true);setError('');try{if(file.name.toLowerCase().endsWith('.json')){const content=JSON.parse(await file.text());const preview=content?.content??content;await adminApi.createOfficial({content:preview});}else{const bytes=new Uint8Array(await file.arrayBuffer());const imported=await importExam(bytes);let b='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)b+=String.fromCharCode(...bytes.subarray(i,i+chunk));const packageBase64=btoa(b);await adminApi.createOfficial({id:imported.content.id,title:imported.content.title,subject:imported.content.subject,grade:imported.content.grade,version:imported.content.version,contentHash:imported.contentHash,packageBase64,questionCount:imported.content.questions.length});}await load()}catch(e){setError(e instanceof Error?e.message:'Đề không hợp lệ')}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm('Xóa Official Exam? Đề sẽ bị unpublish; các bản đã tải về không tự động bị xóa.'))return;setBusy(true);setError('');try{await adminApi.deleteOfficial(id);await load()}catch(e){setError(e instanceof Error?e.message:'Không thể xóa đề')}finally{setBusy(false)}}
 async function publish(id:string,published:boolean){setBusy(true);setError('');try{await adminApi.updateOfficial(id,{published});await load()}catch(e){setError(e instanceof Error?e.message:'Không thể cập nhật đề')}finally{setBusy(false)}}
 return <>{error&&<p className="form-error">{error}</p>}<div className="card overflow-auto"><div className="p-3 flex items-center justify-between gap-3 flex-wrap"><h2 className="font-bold">Đề chính thức</h2><label className="admin-primary-btn cursor-pointer">{busy?'Đang xử lý…':'Import .exam / JSON'}<input className="hidden" type="file" accept=".exam,.json,application/json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label></div><table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-3">Title</th><th className="p-3">Subject</th><th className="p-3">Version</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows===undefined?[0,1,2].map(i=><tr key={i} className="border-t border-[var(--line)]">{[0,1,2,3,4].map(c=><td key={c} className="p-3"><Skeleton className="h-5 w-16"/></td>)}</tr>):rows.map(e=><tr key={e.id} className="border-t border-[var(--line)]"><td className="p-3 font-semibold">{e.title}</td><td className="p-3">{e.subject}</td><td className="p-3">v{e.version}</td><td className="p-3">{e.deletedAt?'Unpublished':'Published'}</td><td className="p-3 flex gap-2">{e.deletedAt?<button className="btn-secondary" disabled={busy} onClick={()=>void publish(e.id,true)}>Publish</button>:<button className="btn-secondary" disabled={busy} onClick={()=>void publish(e.id,false)}>Unpublish</button>}<button className="btn-secondary text-grade" disabled={busy} onClick={()=>void remove(e.id)}>Xóa</button></td></tr>)}</tbody></table></div></>;}

function UserExams(){const [rows,setRows]=useState<AdminExamRow[]>();const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const limit=20;
 useEffect(()=>{adminApi.exams(page,limit,query).then(r=>{setRows(r.exams);setTotal(r.total)}).catch(e=>setError(e instanceof Error?e.message:'Không tải được danh sách'))},[page,query]);
 async function remove(e:AdminExamRow){if(!window.confirm(`Gỡ đề "${e.title||e.entityId}" của user này? Đề sẽ biến mất khỏi kho của họ ở lần sync sau.`))return;setBusy(true);try{await adminApi.deleteUserExam(e.ownerUserId,e.entityId);const r=await adminApi.exams(page,limit,query);setRows(r.exams);setTotal(r.total)}catch(err){alert(err instanceof Error?err.message:'Không xóa được')}finally{setBusy(false)}}
 return <>{error&&<p className="form-error">{error}</p>}<div className="card overflow-auto"><div className="p-3 flex items-center justify-between gap-3 flex-wrap"><h2 className="font-bold">Đề của người dùng <span className="muted font-normal text-sm">({total})</span></h2><div className="flex gap-2"><input className="input" placeholder="Tìm theo tên đề hoặc exam ID" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){setPage(1);setQuery(search)}}}/><button className="btn-secondary" onClick={()=>{setPage(1);setQuery(search)}}>Tìm</button></div></div>
 <table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-3">Tên đề</th><th className="p-3">Exam ID</th><th className="p-3">Chủ sở hữu</th><th className="p-3">Số câu</th><th className="p-3">Cập nhật</th><th className="p-3">Action</th></tr></thead><tbody>
 {rows===undefined?[0,1,2].map(i=><tr key={i} className="border-t border-[var(--line)]">{[0,1,2,3,4,5].map(c=><td key={c} className="p-3"><Skeleton className="h-5 w-16"/></td>)}</tr>)
 :rows.length===0?<tr><td className="p-3 muted" colSpan={6}>Không có đề nào.</td></tr>
 :rows.map(e=><tr key={`${e.profileId}:${e.entityId}`} className="border-t border-[var(--line)]"><td className="p-3 font-semibold max-w-64 truncate">{e.title||'(không tên)'}</td><td className="p-3 font-mono text-xs">{e.entityId}</td><td className="p-3"><Link className="admin-text-link" to={`/admin/users/${e.ownerUserId}`}>{e.ownerUserId.slice(0,8)}…</Link></td><td className="p-3 tabular-nums">{e.questionCount}</td><td className="p-3">{new Date(e.updatedAt).toLocaleString('vi-VN')}</td><td className="p-3"><button className="btn-secondary text-grade" disabled={busy} onClick={()=>void remove(e)}>Gỡ đề</button></td></tr>)}
 </tbody></table></div>
 <div className="flex justify-between items-center text-sm"><button className="btn-secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Trước</button><span>Trang {page}{total?` / ${Math.max(1,Math.ceil(total/limit))}`:''}</span><button className="btn-secondary" disabled={page*limit>=total} onClick={()=>setPage(page+1)}>Sau</button></div></>;}
