import { useEffect,useState } from 'react';
import { useParams } from 'react-router-dom';
import { adminApi, type AdminExamRow, type AdminShareRow, type AuthUser, type SessionInfo, type UserActivityStats } from '../../infrastructure/api/auth';
export function AdminUserDetailPage(){
 const{id}=useParams();const[data,setData]=useState<{user:AuthUser;stats:UserActivityStats;sessions:SessionInfo[]}>();const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[form,setForm]=useState({displayName:'',email:'',role:'USER'});
 const load=()=>{if(id)void adminApi.user(id).then(d=>{setData(d);setForm({displayName:d.user?.name??'',email:d.user?.email??'',role:d.user?.role??'USER'})}).catch(e=>setError(e instanceof Error?e.message:'Không thể tải user'))};
 useEffect(()=>{load()},[id]);
 async function save(){if(!id)return;setSaving(true);try{const r=await adminApi.updateUser(id,{displayName:form.displayName,email:form.email,role:form.role as 'USER'|'ADMIN'});setData(d=>d?{...d,user:r.user}:d);alert('Đã lưu dữ liệu tài khoản.')}catch(e){alert(e instanceof Error?e.message:'Không thể lưu')}finally{setSaving(false)}}
 async function restriction(status:'ACTIVE'|'SUSPENDED'|'BANNED'|'LOCKED'|'LIMITED'){if(!id)return;try{await adminApi.restrictUser(id,status);await load()}catch(e){alert(e instanceof Error?e.message:'Không thể cập nhật trạng thái')}}
 async function remove(){if(!id||!window.confirm('Xóa tài khoản và dữ liệu liên quan?'))return;try{await adminApi.deleteUser(id);alert('Đã xóa tài khoản.')}catch(e){alert(e instanceof Error?e.message:'Không thể xóa')}}
 if(error)return <div className="page-stack"><p className="form-error">{error}</p></div>;
 const u=data?.user,s=data?.stats;
 return <div className="page-stack max-w-5xl mx-auto"><section className="page-hero"><div><span className="eyebrow">ADMIN USER</span><h1>{u?.name??u?.username??'User'}</h1><p>@{u?.username} · <span className="font-semibold">{u?.status}</span></p></div></section>
 <section className="card space-y-4"><div><h2 className="font-bold">Sửa dữ liệu tài khoản</h2><p className="text-sm muted">Username/ID được giữ cố định; các thông tin quản trị có thể chỉnh ở đây.</p></div><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Username<input className="input mt-1 bg-[var(--surface-2)]" value={u?.username??''} disabled/></label><label className="text-sm">Email<input className="input mt-1" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="text-sm">Tên hiển thị<input className="input mt-1" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label className="text-sm">Quyền<select className="select mt-1 w-full" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select></label></div><button className="btn-primary" disabled={saving} onClick={()=>void save()}>{saving?'Đang lưu…':'Lưu thay đổi'}</button></section>
 <section className="card"><h2 className="font-bold">Trạng thái tài khoản</h2><div className="flex flex-wrap gap-2 mt-3"><button className="btn-secondary text-pass" onClick={()=>void restriction('ACTIVE')}>Mở khóa</button><button className="btn-secondary text-warn" onClick={()=>void restriction('SUSPENDED')}>Khóa tạm thời</button><button className="btn-secondary text-warn" onClick={()=>void restriction('LIMITED')}>Giới hạn</button><button className="btn-secondary text-grade" onClick={()=>void restriction('BANNED')}>Ban</button><button className="btn-secondary text-grade" onClick={()=>void remove()}>Xóa tài khoản</button></div></section>
 <section className="card"><h2 className="font-bold">Account</h2><div className="grid sm:grid-cols-2 gap-3 mt-4"><Info k="ID" v={u?.id}/><Info k="Role" v={u?.role}/><Info k="Created" v={u?.createdAt?new Date(u.createdAt).toLocaleString('vi-VN'):''}/><Info k="Last login" v={u?.lastLoginAt?new Date(u.lastLoginAt).toLocaleString('vi-VN'):'—'}/></div></section>
 <section className="stat-grid"><Stat k="Bài làm" v={s?.total}/><Stat k="Thi đấu" v={s?.tournament}/><Stat k="Luyện tập" v={s?.practice}/><Stat k="English" v={s?.english}/><Stat k="Đề" v={s?.exams}/><Stat k="Share" v={s?.shares}/><Stat k="Login fail" v={s?.loginFails}/><Stat k="Rate limit" v={s?.rateLimited}/><Stat k="Warning" v={s?.warnings}/><Stat k="Suspicious" v={s?.suspicious}/></section>
 <section className="card"><h2 className="font-bold">Sessions</h2><div className="space-y-2 mt-3">{(data?.sessions??[]).map((x:any)=><div key={x.id} className="border rounded-xl p-3 text-sm"><b>{x.userAgent??'Unknown browser'}</b><div className="muted">Last active: {new Date(x.lastSeenAt).toLocaleString('vi-VN')}</div></div>)}</div><button className="btn-secondary mt-4" onClick={()=>{if(!id)return;adminApi.forceLogout(id).then(()=>{alert('Đã revoke tất cả session.');load()}).catch(e=>alert(e instanceof Error?e.message:'Không thể đăng xuất'))}}>Đăng xuất tất cả thiết bị</button></section>
 <UserExamsAndShares userId={id}/></div>
}
function Info({k,v}:{k:string;v:any}){return <div className="rounded-xl bg-[var(--surface-2)] p-3"><div className="text-xs muted">{k}</div><div className="font-medium break-all">{v||'—'}</div></div>}
function UserExamsAndShares({userId}:{userId?:string}){
 const[exams,setExams]=useState<AdminExamRow[]>();const[examsTotal,setExamsTotal]=useState(0);const[examPage,setExamPage]=useState(1);const[shares,setShares]=useState<AdminShareRow[]>();const[busy,setBusy]=useState(false);
 const loadExams=()=>{if(userId)adminApi.userExams(userId,examPage,20).then(r=>{setExams(r.exams);setExamsTotal(r.total)}).catch(()=>setExams([]))};
 useEffect(()=>{loadExams()},[userId,examPage]);
 useEffect(()=>{if(userId)adminApi.userShares(userId).then(r=>setShares(r.shares)).catch(()=>setShares([]))},[userId]);
 async function removeExam(e:AdminExamRow){if(!window.confirm(`Gỡ đề "${e.title||e.entityId}"? Sẽ biến mất khỏi kho của user ở lần sync sau.`))return;setBusy(true);try{await adminApi.deleteUserExam(userId??'',e.entityId);loadExams()}catch(err){alert(err instanceof Error?err.message:'Không xóa được')}finally{setBusy(false)}}
 return <>
 <section className="card overflow-auto"><h2 className="font-bold p-3">Đề của user <span className="muted font-normal text-sm">({examsTotal})</span></h2>
 <table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-3">Tên đề</th><th className="p-3">Exam ID</th><th className="p-3">Số câu</th><th className="p-3">Cập nhật</th><th className="p-3">Action</th></tr></thead><tbody>
 {exams===undefined?<tr><td className="p-3 muted" colSpan={5}>Đang tải…</td></tr>:exams.length===0?<tr><td className="p-3 muted" colSpan={5}>User chưa có đề nào.</td></tr>
 :exams.map(e=><tr key={e.entityId} className="border-t border-[var(--line)]"><td className="p-3 font-semibold max-w-64 truncate">{e.title||'(không tên)'}</td><td className="p-3 font-mono text-xs">{e.entityId}</td><td className="p-3 tabular-nums">{e.questionCount}</td><td className="p-3">{new Date(e.updatedAt).toLocaleString('vi-VN')}</td><td className="p-3"><button className="btn-secondary text-grade" disabled={busy} onClick={()=>void removeExam(e)}>Gỡ đề</button></td></tr>)}
 </tbody></table>
 {examsTotal>20&&<div className="flex justify-between items-center text-sm p-3"><button className="btn-secondary" disabled={examPage<=1} onClick={()=>setExamPage(examPage-1)}>Trước</button><span>Trang {examPage}</span><button className="btn-secondary" disabled={examPage*20>=examsTotal} onClick={()=>setExamPage(examPage+1)}>Sau</button></div>}</section>
 <section className="card overflow-auto"><h2 className="font-bold p-3">Mã chia sẻ đang hoạt động</h2>
 <table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-3">Code</th><th className="p-3">Loại</th><th className="p-3">Lượt tải</th><th className="p-3">Tạo</th><th className="p-3">Hết hạn</th></tr></thead><tbody>
 {shares===undefined?<tr><td className="p-3 muted" colSpan={5}>Đang tải…</td></tr>:shares.length===0?<tr><td className="p-3 muted" colSpan={5}>User chưa chia sẻ gì.</td></tr>
 :shares.map(s=><tr key={s.shareId} className="border-t border-[var(--line)]"><td className="p-3 font-mono font-semibold">{s.code}</td><td className="p-3">{s.packageType==='vocabularySet'?'Từ vựng':'Đề'}</td><td className="p-3 tabular-nums">{s.accessCount??0}</td><td className="p-3">{new Date(s.createdAt).toLocaleString('vi-VN')}</td><td className="p-3">{s.expiresAt?new Date(s.expiresAt).toLocaleString('vi-VN'):'Không hết hạn'}</td></tr>)}
 </tbody></table></section></>;
}
function Stat({k,v}:{k:string;v:any}){return <div className="card"><div className="text-xs muted">{k}</div><div className="text-xl font-bold mt-1">{v??'—'}</div></div>}
