import { useEffect,useState } from 'react';
import { useParams } from 'react-router-dom';
import { adminApi } from '../../infrastructure/api/auth';
export function AdminUserDetailPage(){
 const{id}=useParams();const[data,setData]=useState<any>();const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[form,setForm]=useState({displayName:'',email:'',role:'USER'});
 const load=()=>{if(id)void adminApi.user(id).then(d=>{setData(d);setForm({displayName:d.user?.name??'',email:d.user?.email??'',role:d.user?.role??'USER'})}).catch(e=>setError(e instanceof Error?e.message:'Không thể tải user'))};
 useEffect(()=>{load()},[id]);
 async function save(){if(!id)return;setSaving(true);try{const r=await adminApi.updateUser(id,{displayName:form.displayName,email:form.email,role:form.role as 'USER'|'ADMIN'});setData((d:any)=>({...d,user:r.user}));alert('Đã lưu dữ liệu tài khoản.')}catch(e){alert(e instanceof Error?e.message:'Không thể lưu')}finally{setSaving(false)}}
 async function restriction(status:'ACTIVE'|'SUSPENDED'|'BANNED'|'LOCKED'|'LIMITED'){if(!id)return;try{await adminApi.restrictUser(id,status);await load()}catch(e){alert(e instanceof Error?e.message:'Không thể cập nhật trạng thái')}}
 async function remove(){if(!id||!window.confirm('Xóa tài khoản và dữ liệu liên quan?'))return;try{await adminApi.deleteUser(id);alert('Đã xóa tài khoản.')}catch(e){alert(e instanceof Error?e.message:'Không thể xóa')}}
 if(error)return <div className="page-stack"><p className="form-error">{error}</p></div>;
 const u=data?.user,s=data?.stats;
 return <div className="page-stack max-w-5xl mx-auto"><section className="page-hero"><div><span className="eyebrow">ADMIN USER</span><h1>{u?.name??u?.username??'User'}</h1><p>@{u?.username} · <span className="font-semibold">{u?.status}</span></p></div></section>
 <section className="card space-y-4"><div><h2 className="font-bold">Sửa dữ liệu tài khoản</h2><p className="text-sm text-slate-500">Username/ID được giữ cố định; các thông tin quản trị có thể chỉnh ở đây.</p></div><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Username<input className="input mt-1 bg-slate-50" value={u?.username??''} disabled/></label><label className="text-sm">Email<input className="input mt-1" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="text-sm">Tên hiển thị<input className="input mt-1" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label className="text-sm">Quyền<select className="select mt-1 w-full" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select></label></div><button className="btn-primary" disabled={saving} onClick={()=>void save()}>{saving?'Đang lưu…':'Lưu thay đổi'}</button></section>
 <section className="card"><h2 className="font-bold">Trạng thái tài khoản</h2><div className="flex flex-wrap gap-2 mt-3"><button className="btn-secondary text-emerald-700" onClick={()=>void restriction('ACTIVE')}>Mở khóa</button><button className="btn-secondary text-amber-700" onClick={()=>void restriction('SUSPENDED')}>Khóa tạm thời</button><button className="btn-secondary text-orange-700" onClick={()=>void restriction('LIMITED')}>Giới hạn</button><button className="btn-secondary text-red-600" onClick={()=>void restriction('BANNED')}>Ban</button><button className="btn-secondary text-red-700" onClick={()=>void remove()}>Xóa tài khoản</button></div></section>
 <section className="card"><h2 className="font-bold">Account</h2><div className="grid sm:grid-cols-2 gap-3 mt-4"><Info k="ID" v={u?.id}/><Info k="Role" v={u?.role}/><Info k="Created" v={u?.createdAt?new Date(u.createdAt).toLocaleString('vi-VN'):''}/><Info k="Last login" v={u?.lastLoginAt?new Date(u.lastLoginAt).toLocaleString('vi-VN'):'—'}/></div></section>
 <section className="stat-grid"><Stat k="Bài làm" v={s?.total}/><Stat k="Thi đấu" v={s?.tournament}/><Stat k="Luyện tập" v={s?.practice}/><Stat k="English" v={s?.english}/><Stat k="Đề" v={s?.exams}/><Stat k="Share" v={s?.shares}/><Stat k="Login fail" v={s?.loginFails}/><Stat k="Rate limit" v={s?.rateLimited}/><Stat k="Warning" v={s?.warnings}/><Stat k="Suspicious" v={s?.suspicious}/></section>
 <section className="card"><h2 className="font-bold">Sessions</h2><div className="space-y-2 mt-3">{(data?.sessions??[]).map((x:any)=><div key={x.id} className="border rounded-xl p-3 text-sm"><b>{x.userAgent??'Unknown browser'}</b><div className="text-slate-500">Last active: {new Date(x.lastSeenAt).toLocaleString('vi-VN')}</div></div>)}</div><button className="btn-secondary mt-4" onClick={()=>id&&adminApi.forceLogout(id).then(()=>alert('Đã revoke tất cả session.'))}>Đăng xuất tất cả thiết bị</button></section></div>
}
function Info({k,v}:{k:string;v:any}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-400">{k}</div><div className="font-medium break-all">{v||'—'}</div></div>}
function Stat({k,v}:{k:string;v:any}){return <div className="card"><div className="text-xs text-slate-400">{k}</div><div className="text-xl font-bold mt-1">{v??'—'}</div></div>}
