import { useEffect,useRef,useState } from 'react';
import { Link } from 'react-router-dom';
import { adminApi, type AuthUser } from '../../infrastructure/api/auth';
import { Skeleton } from '../components/Skeleton';

const statusStyle=(s:string)=>s==='ACTIVE'?'bg-pass-soft text-pass':s==='BANNED'?'bg-grade-soft text-grade':s==='SUSPENDED'?'bg-warn-soft text-warn':'bg-[var(--surface-2)] text-[var(--ink)]';

export function AdminUsersPage(){
 const [rows,setRows]=useState<AuthUser[]>();const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 // Search only applies via committed `query` (Tìm/Enter), so the fetch fires once
 // from the effect instead of racing a manual load() built from stale state.
 // The seq guard drops responses from superseded requests (old page + new filter).
 const seq=useRef(0);
 const load=()=>{const my=++seq.current;adminApi.users(page,50,query,status).then(r=>{if(seq.current!==my)return;setRows(r.users);setTotal(r.total);setError('')}).catch(e=>{if(seq.current!==my)return;setRows([]);setTotal(0);setError(e instanceof Error?e.message:'Không thể tải')})};
 useEffect(()=>{void load()},[page,status,query]);
 async function apply(id:string,s:'ACTIVE'|'SUSPENDED'|'BANNED'|'LOCKED'|'LIMITED'){setBusy(id);try{await adminApi.restrictUser(id,s);await load()}catch(e){alert(e instanceof Error?e.message:'Không thể cập nhật')}finally{setBusy('')}}
 async function reset(id:string){const p=window.prompt('Nhập temporary password (ít nhất 10 ký tự):');if(!p)return;try{await adminApi.resetPassword(id,p);alert('Đã reset password và revoke session. User phải đổi password khi đăng nhập.')}catch(e){alert(e instanceof Error?e.message:'Không thể reset password')}}
 async function remove(id:string){if(!window.confirm('Xóa vĩnh viễn dữ liệu tài khoản này? Dữ liệu học tập, share và session liên quan sẽ bị xóa.'))return;setBusy(id);try{await adminApi.deleteUser(id);if(rows&&rows.length===1&&page>1)setPage(page-1);else await load()}catch(e){alert(e instanceof Error?e.message:'Không thể xóa')}finally{setBusy('')}}
 return <div className="page-stack max-w-7xl mx-auto"><section className="page-hero"><div><span className="eyebrow">ADMIN</span><h1>Quản lý người dùng</h1><p>Ban, khóa, giới hạn, sửa thông tin, reset mật khẩu và xóa tài khoản.</p></div></section>
 {error&&<p className="form-error">{error}</p>}
<div className="card"><div className="flex flex-wrap gap-2"><input className="input flex-1 min-w-60" placeholder="Tên / username / user ID" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){setPage(1);setQuery(search)}}}/><select className="select" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Tất cả status</option><option>ACTIVE</option><option>SUSPENDED</option><option>BANNED</option><option>LOCKED</option><option>LIMITED</option></select><button className="btn-primary" onClick={()=>{setPage(1);setQuery(search)}}>Tìm</button></div></div>
 <div className="card overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-3">Username</th><th className="p-3">Tên</th><th className="p-3">Role</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3">Action</th></tr></thead><tbody>{rows===undefined?[0,1,2,3,4,5].map(i=><tr key={i} className="border-t border-[var(--line)]">{[0,1,2,3,4,5].map(c=><td key={c} className="p-3"><Skeleton className="h-5 w-20"/></td>)}</tr>):rows.map(u=><tr key={u.id} className="border-t border-[var(--line)]"><td className="p-3 font-semibold"><Link className="text-accent-strong hover:underline" to={`/admin/users/${u.id}`}>{u.username}</Link></td><td className="p-3">{u.name??u.username}</td><td className="p-3"><span className="rounded-full bg-accent-soft text-accent-strong px-2 py-1 text-xs font-semibold">{u.role}</span></td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusStyle(u.status)}`}>{u.status}</span></td><td className="p-3">{new Date(u.createdAt).toLocaleString('vi-VN')}</td><td className="p-3"><div className="flex flex-wrap gap-2">{u.role!=='ADMIN'&&<><Link className="btn-secondary" to={`/admin/users/${u.id}`}>Sửa</Link>{u.status!=='BANNED'&&<button className="btn-secondary text-grade" disabled={busy===u.id} onClick={()=>void apply(u.id,'BANNED')}>Ban</button>}{u.status==='BANNED'&&<button className="btn-secondary text-pass" disabled={busy===u.id} onClick={()=>void apply(u.id,'ACTIVE')}>Gỡ ban</button>}{u.status!=='SUSPENDED'&&u.status!=='BANNED'&&<button className="btn-secondary text-warn" disabled={busy===u.id} onClick={()=>void apply(u.id,'SUSPENDED')}>Khóa</button>}{u.status==='SUSPENDED'&&<button className="btn-secondary text-pass" disabled={busy===u.id} onClick={()=>void apply(u.id,'ACTIVE')}>Mở khóa</button>}<button className="btn-secondary" disabled={busy===u.id} onClick={()=>void reset(u.id)}>Reset MK</button><button className="btn-secondary text-grade" disabled={busy===u.id} onClick={()=>void remove(u.id)}>Xóa</button></>}</div></td></tr>)}</tbody></table></div>
 <div className="flex justify-between items-center text-sm"><button className="btn-secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Trước</button><span>Trang {page} · {total} user</span><button className="btn-secondary" disabled={page*50>=total} onClick={()=>setPage(page+1)}>Sau</button></div></div>
}
