import { useEffect,useRef,useState } from 'react';
import { adminApi, type AiPoolKey } from '../../infrastructure/api/auth';
export function AdminAiPage(){
 const [data,setData]=useState<{keys:AiPoolKey[]}>();const [limits,setLimits]=useState({chatPerMinute:20,explainPerMinute:10,jsonPerMinute:5});const [name,setName]=useState('');const [key,setKey]=useState('');const [model,setModel]=useState('gemini-3.1-flash-lite');const [rpmLimit,setRpmLimit]=useState(15);const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false);const [adding,setAdding]=useState(false);const limitsLoaded=useRef(false);
 // Load server limits only on first load: overwriting them on every key/toggle
 // refresh silently reverted the admin's unsaved limit edits.
 const load=()=>{void Promise.all([adminApi.aiKeys(),adminApi.aiSettings()]).then(([keys,settings])=>{setData(keys);if(settings?.limits&&!limitsLoaded.current){setLimits(settings.limits);limitsLoaded.current=true}}).catch(e=>setMsg(e.message))};useEffect(load,[]);
 async function add(){if(!name||!key||adding)return;setAdding(true);try{await adminApi.addAiKey(name,key,model,rpmLimit);setName('');setKey('');setMsg('Đã thêm API key và lưu vào SQLite.');load()}catch(e){setMsg(e instanceof Error?e.message:'Không thể thêm')}finally{setAdding(false)}}
 async function saveLimits(){setSaving(true);setMsg('');try{const clean={chatPerMinute:Math.max(0,Math.floor(limits.chatPerMinute)),explainPerMinute:Math.max(0,Math.floor(limits.explainPerMinute)),jsonPerMinute:Math.max(0,Math.floor(limits.jsonPerMinute))};const r=await adminApi.setAiSettings(clean);setLimits(r.limits);setMsg('Đã lưu giới hạn AI. Áp dụng cho từng tài khoản theo phút.')}catch(e){setMsg(e instanceof Error?e.message:'Không thể lưu')}finally{setSaving(false)}}
 return <div className="space-y-5"><div className="admin-page-heading"><div><span className="admin-eyebrow">AI & GEMINI</span><h1>Quản lý AI</h1><p>Pool Gemini server-side. Mỗi API key có giới hạn riêng và tự động chuyển sang key kế tiếp khi đầy quota phút.</p></div></div>
 <section className="card space-y-3"><div><h2 className="font-semibold">Giới hạn sử dụng AI</h2><p className="text-sm muted">Số lượt tối đa mỗi phút cho <b>mỗi tài khoản</b>. Đặt 0 để khóa loại AI đó.</p></div><div className="grid md:grid-cols-3 gap-3"><label className="text-sm">AI chat<input className="input mt-1" type="number" min="0" max="1000" value={limits.chatPerMinute} onChange={e=>setLimits({...limits,chatPerMinute:Number(e.target.value)})}/></label><label className="text-sm">Giải thích câu hỏi<input className="input mt-1" type="number" min="0" max="1000" value={limits.explainPerMinute} onChange={e=>setLimits({...limits,explainPerMinute:Number(e.target.value)})}/></label><label className="text-sm">Sửa JSON<input className="input mt-1" type="number" min="0" max="1000" value={limits.jsonPerMinute} onChange={e=>setLimits({...limits,jsonPerMinute:Number(e.target.value)})}/></label></div><button className="btn-primary" disabled={saving} onClick={()=>void saveLimits()}>{saving?'Đang lưu…':'Lưu giới hạn'}</button></section>
 <section className="card space-y-3"><h2 className="font-semibold">Thêm Gemini API</h2><div className="grid md:grid-cols-4 gap-3"><input className="input" placeholder="Tên key" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="AIza..." type="password" value={key} onChange={e=>setKey(e.target.value)}/><input className="input" placeholder="gemini-3.1-flash-lite" value={model} onChange={e=>setModel(e.target.value)}/><input className="input" type="number" min="1" max="1000" value={rpmLimit} onChange={e=>setRpmLimit(Number(e.target.value))}/></div><p className="text-xs muted">Mặc định 15 request/phút cho từng key. Khi một key đủ 15 request hoặc gặp 429/5xx, server tự chuyển key khác. Reservation được thực hiện nguyên tử trên SQLite để request đồng thời không thể vượt 15.</p><button className="btn-primary" disabled={adding} onClick={()=>void add()}>{adding?'Đang thêm…':'Thêm API key'}</button>{msg&&<p className="text-sm muted">{msg}</p>}</section>
 <section className="card"><h2 className="font-semibold mb-3">Pool API hiện tại</h2><div className="space-y-2">{(data?.keys??[]).map((k:any)=><div key={k.id} className="flex items-center justify-between gap-3 border rounded-xl p-3"><div><strong>{k.name}</strong><p className="text-xs muted">{k.maskedKey} · {k.model} · {k.rpmLimit ?? 15} RPM · lỗi {k.failures}</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>void adminApi.setAiKey(k.id,!k.enabled).then(load)}>{k.enabled?'Tắt':'Bật'}</button>{!k.id.startsWith('env-gemini-')&&<button className="btn-secondary text-grade" onClick={()=>void adminApi.deleteAiKey(k.id).then(load)}>Xóa</button>}</div></div>)}{!(data?.keys?.length)&&<p className="text-sm muted">Chưa có Gemini API. Hãy thêm key hoặc đặt GEMINI_API_KEY(S) trên server.</p>}</div></section>
 </div>
}
