import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { examService } from '../../domain/exam/exam.service';
import { examRepository } from '../../domain/exam/exam.repository';
import { questionService } from '../../domain/exam/question.service';
import type { Exam, Question } from '../../domain/exam/exam.types';
import { QuestionEditor } from '../components/exam/QuestionEditor';
import { Skeleton } from '../components/Skeleton';
import { Breadcrumbs } from '../components/Breadcrumbs';
import { durationFromMinutes, durationToMinutes } from "@exam/utils";

export function ExamEditorPage(){const {examId}=useParams();const nav=useNavigate();const [exam,setExam]=useState<Exam|null>(null);const [questions,setQuestions]=useState<Question[]>([]);const [saving,setSaving]=useState(false);const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!examId)return;try{setExam(await examService.getExam(examId));setQuestions(await examRepository.getQuestionsByExam(examId));setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'Không thể mở đề')}})()},[examId]);
 const persist=useCallback(async(e:Exam,qs:Question[])=>{setSaving(true);try{await examService.updateExam(e.id,{title:e.title,description:e.description,subject:e.subject,grade:e.grade,duration:e.duration});for(const q of qs) await questionService.updateQuestion(q);await examService.refreshQuestionCount(e.id);}catch(e){setError(e instanceof Error?e.message:'Lưu thất bại')}finally{setSaving(false)}},[]);
 useEffect(()=>{if(!exam||!loaded)return;const t=setTimeout(()=>persist(exam,questions),400);return()=>clearTimeout(t)},[exam,questions,persist]);
 if(error)return <div className="card text-grade">{error}</div>;if(!exam)return <div className="space-y-4"><div className="card space-y-3"><Skeleton className="h-8 w-2/3" /><div className="grid grid-cols-2 gap-2">{[0,1,2,3].map(i=><Skeleton key={i} className="h-10 rounded-xl"/>)}</div></div><div className="card space-y-3"><Skeleton className="h-5 w-1/2" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-5/6" /></div></div>;
 const add=async()=>{const q=await questionService.addQuestion({examId:exam.id,type:'ABCD',content:'Câu hỏi mới',points:1,options:[{id:`${exam.id}_a_${questions.length}`,text:'Lựa chọn A'},{id:`${exam.id}_b_${questions.length}`,text:'Lựa chọn B'},{id:`${exam.id}_c_${questions.length}`,text:'Lựa chọn C'},{id:`${exam.id}_d_${questions.length}`,text:'Lựa chọn D'}],correctOptionId:`${exam.id}_a_${questions.length}`});setQuestions([...questions,q])};
 const remove=async(id:string)=>{await questionService.deleteQuestion(id);const next=questions.filter(q=>q.id!==id).map((q,i)=>({...q,order:i}));setQuestions(next);await examService.refreshQuestionCount(exam.id)};
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><Breadcrumbs items={[{ label: "Trang chủ", to: "/" }, { label: "Kho đề", to: "/library" }, { label: exam.title, to: `/library/${exam.id}` }, { label: "Chỉnh sửa" }]} /><span className="text-sm muted">{saving?'Đang lưu...':'Đã lưu trên thiết bị'}</span></div><div className="card space-y-3"><input className="input text-xl font-semibold" value={exam.title} onChange={e=>setExam({...exam,title:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className="input" value={exam.subject} placeholder="Môn" onChange={e=>setExam({...exam,subject:e.target.value})}/><input className="input" type="number" min="1" max="12" value={exam.grade??''} placeholder="Lớp" onChange={e=>setExam({...exam,grade:e.target.value?Number(e.target.value):undefined})}/><input className="input" type="number" min="1" step="any" value={exam.duration===undefined?'':durationToMinutes(exam.duration)} placeholder="Thời gian (phút)" onChange={e=>setExam({...exam,duration:e.target.value!==''?durationFromMinutes(Number(e.target.value)):undefined})}/><input className="input" value={exam.description??''} placeholder="Mô tả" onChange={e=>setExam({...exam,description:e.target.value})}/></div></div><div className="space-y-3">{questions.map((q,i)=><QuestionEditor key={q.id} question={q} onChange={q2=>setQuestions(questions.map(x=>x.id===q.id?q2:x))} onDelete={()=>remove(q.id)} onMove={async d=>{const j=i+d;if(j<0||j>=questions.length)return;const next=[...questions];[next[i],next[j]]=[next[j],next[i]];const normalized=next.map((x,k)=>({...x,order:k}));setQuestions(normalized);await questionService.reorderQuestions(exam.id,normalized.map(x=>x.id))}}/>)}<button className="btn-primary w-full" onClick={add}>+ Thêm câu</button></div></div>}
