import { Link, useNavigate, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import { examService } from "../../domain/exam/exam.service";
import { examRepository } from "../../domain/exam/exam.repository";
import { examFileService } from "../../domain/exam/exam.file.service";
import type { Exam, Question } from "../../domain/exam/exam.types";
import { RichContent } from "../components/exam/RichContent";
import { createExamShare } from "../../domain/share/exam-share.service";
import { AppIcon } from "../components/AppIcon";

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename.endsWith(".exam") ? filename : `${filename}.exam`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function ExamDetailPage() {
  const { examId } = useParams(); const nav = useNavigate();
  const [exam, setExam] = useState<Exam>(); const [qs, setQs] = useState<Question[]>([]); const [exporting, setExporting] = useState(false); const [notice, setNotice] = useState(""); const [shareBusy, setShareBusy] = useState(false); const [shareCode, setShareCode] = useState(""); const [deleteOpen, setDeleteOpen] = useState(false); const [deleting, setDeleting] = useState(false);
  const load = async () => { if (!examId) return; setExam(await examService.getExam(examId)); setQs(await examRepository.getQuestionsByExam(examId)); };
  useEffect(() => { void load(); }, [examId]);
  if (!exam) return <div className="empty-state"><div className="empty-icon"><AppIcon name="library" size={28} /></div><h2>Đang tải đề…</h2></div>;
  const readOnly = exam.source !== "local";
  async function handleExport() { setNotice(""); setExporting(true); try { const { blob, filename } = await examFileService.exportExam(exam.id); if (!blob.size) throw new Error("File xuất ra đang rỗng"); downloadBlob(blob, filename); setNotice(`Đã xuất ${filename}`); } catch (e) { setNotice(`Không thể xuất file: ${e instanceof Error ? e.message : "Lỗi không xác định"}`); } finally { setExporting(false); } }
  async function share() { try { setShareBusy(true); setNotice(""); const result = await createExamShare(exam.id); setShareCode(result.shareCode); try { await navigator.clipboard.writeText(result.shareCode); setNotice(`Đã tạo mã ${result.shareCode} và sao chép vào clipboard.`); } catch { setNotice(`Đã tạo mã ${result.shareCode}.`); } } catch (e) { setNotice(`Không thể chia sẻ: ${e instanceof Error ? e.message : "Lỗi không xác định"}`); } finally { setShareBusy(false); } }
  async function handleDelete() { if (!exam) return; setDeleting(true); try { await examService.deleteExam(exam.id); nav("/library"); } catch (e) { setNotice(`Không thể xóa đề: ${e instanceof Error ? e.message : "Lỗi không xác định"}`); setDeleteOpen(false); } finally { setDeleting(false); } }
  async function copyShareCode() { try { await navigator.clipboard.writeText(shareCode); setNotice("Đã sao chép mã đề."); } catch { setNotice("Trình duyệt không cho phép sao chép tự động."); } }

  return <div className="page-stack max-w-6xl mx-auto">
    <Link to="/library" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-slate-900"><AppIcon name="arrow" size={15} className="rotate-180" />Quay lại Kho đề</Link>
    <section className="card sm:p-7">
      <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-5"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`source-pill ${exam.source}`}>{exam.source === "shared" ? "Đã chia sẻ" : exam.source === "official" ? "Đề gốc" : "Cá nhân"}</span><span className="text-[10px] text-slate-400">v{exam.version}</span></div><h1 className="mt-3 text-2xl sm:text-3xl font-extrabold tracking-tight break-words">{exam.title}</h1><p className="text-sm text-slate-500 mt-2">{exam.subject}{exam.grade ? ` · Lớp ${exam.grade}` : ""}</p></div><button aria-label="Yêu thích" className="w-11 h-11 grid place-items-center rounded-xl border border-slate-200 bg-white text-amber-500 hover:bg-amber-50" onClick={async () => { await examService.favoriteExam(exam.id); void load(); }}><AppIcon name="star" size={21} fill={exam.isFavorite ? "currentColor" : "none"} /></button></div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 mt-6"><InfoStat label="Câu hỏi" value={`${qs.length} câu`} icon="book" /><InfoStat label="Thời gian" value={exam.duration !== undefined ? `${Math.round(exam.duration / 60)} phút` : "Không giới hạn"} icon="clock" /><InfoStat label="Nguồn" value={exam.source === "local" ? "Cá nhân" : exam.source} icon="library" /><InfoStat label="Trạng thái" value="Offline sẵn sàng" icon="check" /></div>
      {exam.description && <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{exam.description}</p>}
      <div className="grid grid-cols-2 sm:flex sm:flex-wrap gap-2 mt-6"><Link className="btn-primary" to={`/practice/${exam.id}`}><AppIcon name="play" size={17} />Luyện tập</Link><Link className="btn-secondary" to={`/tournament/${exam.id}`}><AppIcon name="trophy" size={17} />Thi đấu</Link>{readOnly ? <button className="btn-secondary" onClick={async () => { const copy = await examService.duplicateExam(exam.id); nav(`/library/${copy.id}/edit`); }}><AppIcon name="plus" size={17} />Sao chép</button> : <Link className="btn-secondary" to={`/library/${exam.id}/edit`}><AppIcon name="edit" size={17} />Sửa đề</Link>}<button className="btn-secondary" onClick={handleExport} disabled={exporting}><AppIcon name="download" size={17} />{exporting ? "Đang xuất…" : "Xuất .exam"}</button><button className="btn-secondary" onClick={() => void share()} disabled={shareBusy}><AppIcon name="share" size={17} />{shareBusy ? "Đang tạo…" : "Chia sẻ"}</button>{exam.source === "local" && <button className="btn-secondary text-red-600 border-red-200 hover:bg-red-50" onClick={() => setDeleteOpen(true)}><AppIcon name="shield" size={17} />Xóa đề</button>}</div>
      {shareCode && <div className="mt-4 flex flex-col sm:flex-row sm:items-center gap-3 rounded-2xl border border-indigo-100 bg-indigo-50/70 p-4"><div className="flex-1"><span className="text-[10px] font-extrabold tracking-[.12em] text-indigo-500">MÃ CHIA SẺ</span><div className="mt-1 text-2xl font-black tracking-[.2em] text-indigo-900">{shareCode}</div><p className="mt-1 text-xs text-indigo-700/70">Người khác có thể nhập mã này trong Kho đề.</p></div><button className="btn-secondary" onClick={() => void copyShareCode()}><AppIcon name="share" size={16} />Sao chép mã</button></div>}
      {deleteOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-bold text-slate-900">Bạn có chắc chắn muốn xóa đề này không?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Hành động này sẽ xóa đề vĩnh viễn và không thể hoàn tác.</p><div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={() => setDeleteOpen(false)} disabled={deleting}>Hủy</button><button className="btn-primary !bg-red-600 hover:!bg-red-700" onClick={() => void handleDelete()} disabled={deleting}>{deleting ? "Đang xóa…" : "Xóa vĩnh viễn"}</button></div></div></div>}{notice && <p role="status" className={`mt-3 text-xs ${notice.startsWith("Không thể") ? "text-red-600" : "text-emerald-600"}`}>{notice}</p>}
    </section>
    <section><div className="section-heading mb-3"><div><h2>Danh sách câu hỏi</h2><p>{qs.length} câu trong đề</p></div></div><div className="space-y-2.5">{qs.map((q, i) => <article className="card sm:p-5" key={q.id}><div className="flex items-start gap-3"><span className="question-number">{i + 1}</span><div className="min-w-0 flex-1"><div className="font-semibold leading-6 break-words"><RichContent html={q.content || "(Chưa có nội dung)"} /></div><div className="mt-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>{q.type}</span><span>·</span><span>{q.points} điểm</span></div></div></div></article>)}</div></section>
  </div>;
}

function InfoStat({ label, value, icon }: { label: string; value: string; icon: "book" | "clock" | "library" | "check" }) { return <div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-slate-400"><AppIcon name={icon} size={14} />{label}</div><strong className="block mt-2 text-sm text-slate-800">{value}</strong></div>; }
