import { useEffect, useMemo, useState } from 'react';
import { Skeleton } from '../components/Skeleton';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useProfileStore } from '../../state/profileStore';
import { vocabularySetSessionController } from '../../domain/vocabulary/vocabulary.set.session.controller';
import { VocabularyMCQuestion } from '../components/vocabulary/VocabularyMCQuestion';
import { VocabularyTextQuestion } from '../components/vocabulary/VocabularyTextQuestion';
import { VocabularyLetterOrderQuestion } from '../components/vocabulary/VocabularyLetterOrderQuestion';
import type { VocabQuestionType } from '@exam/shared-types';
import type { SetSessionState } from '../../domain/vocabulary/vocabulary.set.session.service';
const types:[VocabQuestionType,string][]=[['MC_EN_TO_VI','ABCD'],['TEXT_EN_TO_VI','EN → VI'],['TEXT_VI_TO_EN','VI → EN'],['LETTER_ORDER','Sắp xếp chữ']];
export function VocabularySetPracticePage(){const {setId}=useParams();const profile=useProfileStore(s=>s.activeProfile)!;const nav=useNavigate();const [session,setSession]=useState<SetSessionState>();const [mode,setMode]=useState<'ALL'|'WEAK'|'WRONG'|'NEW'|'CUSTOM'>('ALL');const [count,setCount]=useState<number|'all'>('all');const [selectedTypes,setSelectedTypes]=useState<VocabQuestionType[]>(types.map(x=>x[0]));const [draft,setDraft]=useState('');const [feedback,setFeedback]=useState<boolean|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!setId)return;void (async()=>{try{const active=await vocabularySetSessionController.resume(profile.id,setId);if(active)setSession(active);}catch(e){setError(e instanceof Error?e.message:'Không thể khôi phục phiên')}finally{setLoading(false)}})()},[profile.id,setId]);
 useEffect(()=>{if(session){const q=session.questions[session.currentQuestionIndex];setDraft(q?.id?session.answers[q.id]??'':'');setFeedback(null)}},[session?.currentQuestionIndex]);
 const canStart=selectedTypes.length>0; const start=async()=>{if(!setId||!canStart)return;try{const s=await vocabularySetSessionController.create(profile.id,setId,{mode,requestedCount:count,questionTypes:selectedTypes});setSession(s)}catch(e){setError(e instanceof Error?e.message:'Không thể tạo phiên')}};
 async function refresh(){if(!setId||!session)return;setSession(await vocabularySetSessionController.state(profile.id,session.session.id));}
 async function answer(){try{if(!session)return;const r=await vocabularySetSessionController.answer(profile.id,session.session.id,draft);setFeedback(r.correct);await refresh()}catch(e){setError(e instanceof Error?e.message:'Không thể lưu đáp án')}}
 async function next(){try{if(!session||!setId)return;const q=session.questions[session.currentQuestionIndex];if(feedback===null&&q.availability==='available'&&draft.trim())await vocabularySetSessionController.answer(profile.id,session.session.id,draft);if(session.currentQuestionIndex===session.questions.length-1){await vocabularySetSessionController.submit(profile.id,session.session.id);nav(`/vocabulary/sets/${setId}/result`);return;}await vocabularySetSessionController.next(profile.id,session.session.id);await refresh()}catch(e){setError(e instanceof Error?e.message:'Không thể chuyển câu')}}
 if(loading)return <div className="card space-y-4 mx-auto" style={{maxWidth:720}}><Skeleton className="h-4 w-24"/><Skeleton className="h-8 w-2/3"/><Skeleton className="h-12 rounded-xl"/><div className="grid grid-cols-2 gap-2">{[0,1,2,3].map(i=><Skeleton key={i} className="h-12 rounded-xl"/>)}</div></div>; if(error&&!session)return <div className="card text-grade">{error}</div>; if(!session)return <div className="space-y-4"><Link className="text-sm muted" to={`/vocabulary/sets/${setId}`}>← Bộ từ</Link><div className="card"><h1 className="text-2xl font-bold">Smart Practice</h1><div className="grid gap-3 mt-5"><label>Chế độ<select className="input mt-1" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="ALL">Tất cả</option><option value="WEAK">Từ yếu</option><option value="WRONG">Câu sai</option><option value="NEW">Từ mới</option><option value="CUSTOM">Tùy chọn</option></select></label><label>Số câu<select className="input mt-1" value={String(count)} onChange={e=>setCount(e.target.value==='all'?'all':Number(e.target.value))}><option value="5">5</option><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="all">Tất cả</option></select></label><div><p className="text-sm mb-2">Dạng câu hỏi</p><div className="grid grid-cols-2 gap-2">{types.map(([t,label])=><label className="flex gap-2 items-center" key={t}><input type="checkbox" checked={selectedTypes.includes(t)} onChange={e=>setSelectedTypes(x=>e.target.checked?[...x,t]:x.filter(y=>y!==t))}/>{label}</label>)}</div></div><button className="btn-primary" disabled={!canStart} onClick={start}>Bắt đầu</button></div>{error&&<p className="text-grade text-sm mt-3">{error}</p>}</div></div>;
 const q=session.questions[session.currentQuestionIndex]; if(!q)return <div className="card">Không có câu hỏi.</div>; return <div className="space-y-4"><div className="flex justify-between"><Link className="text-sm muted" to={`/vocabulary/sets/${setId}`}>← Thoát</Link><span className="text-sm muted">{session.currentQuestionIndex+1}/{session.questions.length}</span></div><div className="card"><div className="flex gap-1 mb-5">{session.questions.map((x,i)=><button key={x.id} className={`h-2 flex-1 rounded ${i===session.currentQuestionIndex?'bg-accent':session.answers[x.id]!==undefined?'bg-pass':'bg-[var(--line-strong)]'}`} onClick={async()=>{await vocabularySetSessionController.jump(profile.id,session.session.id,i);await refresh()}} />)}</div>{q.type==='MC_EN_TO_VI'?<VocabularyMCQuestion question={q} value={draft} onChange={setDraft}/>:q.type==='LETTER_ORDER'?<VocabularyLetterOrderQuestion question={q} value={draft} onChange={setDraft}/>:<VocabularyTextQuestion question={q} value={draft} onChange={setDraft}/>} {feedback!==null&&<div className="mt-4 p-3 rounded bg-[var(--surface-2)]">{feedback?'✓ Chính xác':'✗ Chưa đúng'}</div>}<button className="btn-primary w-full mt-4" disabled={q.availability!=='available'||!draft||feedback!==null} onClick={answer}>Kiểm tra</button></div><div className="flex gap-2"><button className="btn-secondary" onClick={async()=>{await vocabularySetSessionController.flag(profile.id,session.session.id);await refresh()}}>🚩</button><button className="btn-secondary" disabled={session.currentQuestionIndex===0} onClick={async()=>{await vocabularySetSessionController.previous(profile.id,session.session.id);await refresh()}}>Trước</button><button className="btn-primary flex-1" onClick={next}>{session.currentQuestionIndex===session.questions.length-1?'Nộp bài':'Tiếp'}</button></div></div>;
}
