import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useProfileStore } from "../../state/profileStore";
import { vocabularyController } from "../../domain/vocabulary/vocabulary.controller";
import type { Vocabulary, VocabProgress } from "@exam/shared-types";

export function VocabularyPage(){
 const profile=useProfileStore(s=>s.activeProfile)!; const [items,setItems]=useState<Vocabulary[]>([]); const [progress,setProgress]=useState<Record<string,VocabProgress[]>>({}); const [search,setSearch]=useState(""); const [sort,setSort]=useState("newest"); const [error,setError]=useState("");
 const load=async()=>{const rows=await vocabularyController.list(profile.id);setItems(rows);const entries=await Promise.all(rows.map(async v=>[v.id,await vocabularyController.progress(profile.id,v.id)] as const));setProgress(Object.fromEntries(entries));}; useEffect(()=>{void load()},[profile.id]);
 const visible=useMemo(()=>items.filter(v=>`${v.english} ${v.vietnamese}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>sort==='name'?a.english.localeCompare(b.english):b.updatedAt-a.updatedAt),[items,search,sort]);
 async function remove(id:string){if(!confirm("Xóa từ này? Dữ liệu luyện tập cũ vẫn được giữ cho lịch sử."))return;try{await vocabularyController.delete(profile.id,id);await load()}catch(e){setError(e instanceof Error?e.message:"Không thể xóa")}}
 return <div className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">🧠 Từ vựng</h1><p className="text-sm text-gray-500">Tạo và luyện từ hoàn toàn offline.</p></div><div className="flex gap-2"><Link to="/vocabulary/sets" className="btn-secondary">📚 Bộ từ</Link><Link to="/vocabulary/new" className="btn-primary">+ Thêm từ</Link></div></div><div className="card grid gap-2 sm:grid-cols-[1fr_160px]"><input className="input" placeholder="Tìm từ hoặc nghĩa..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="input" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Mới nhất</option><option value="name">English A-Z</option></select></div>{error&&<p className="text-sm text-red-600">{error}</p>}{visible.length===0?<div className="card text-center py-10"><p className="font-medium">Chưa có từ vựng</p><Link to="/vocabulary/new" className="btn-primary inline-block mt-3">Tạo từ đầu tiên</Link></div>:<div className="space-y-2">{visible.map(v=>{const ps=progress[v.id]??[];const total=ps.reduce((a,p)=>a+p.attemptCount,0),correct=ps.reduce((a,p)=>a+p.correctCount,0);return <div className="card flex items-start justify-between gap-3" key={v.id}><Link className="min-w-0 flex-1" to={`/vocabulary/${v.id}`}><h2 className="font-semibold truncate">{v.english}</h2><p className="text-sm text-gray-500 truncate">{v.vietnamese}</p><p className="text-xs text-gray-400 mt-1">4 dạng câu hỏi · {total?`${Math.round(correct/total*100)}% đúng`:'Chưa luyện'} · {ps.some(x=>x.lastAttemptAt)?`Lần cuối ${new Date(Math.max(...ps.map(x=>x.lastAttemptAt??0))).toLocaleDateString('vi-VN')}`:'Chưa luyện'}</p></Link><div className="flex gap-1"><Link className="btn-secondary text-xs" to={`/vocabulary/${v.id}/edit`}>Sửa</Link><button className="btn-secondary text-xs" onClick={()=>remove(v.id)}>Xóa</button></div></div>})}</div>}</div>
}
