import { chromium } from "@playwright/test";
const base = "http://127.0.0.1:4173";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 1000 } })).newPage();
const suf = Date.now();
await page.goto(base + "/register");
await page.getByPlaceholder("Tên hiển thị").fill("Probe " + suf);
await page.getByPlaceholder("Username").fill("probe_" + suf);
await page.getByPlaceholder("Mật khẩu (ít nhất 10 ký tự)").fill("shot-password-123");
await page.getByPlaceholder("Nhập lại mật khẩu").fill("shot-password-123");
await page.getByRole("button", { name: "Đăng ký & vào học" }).click();
await page.getByRole("heading", { name: /Kho đề/ }).waitFor();
await page.goto(base + "/vocabulary/sets/new");
await page.getByLabel("Tên", { exact: true }).fill("Probe set " + suf);
await page.getByRole("button", { name: "Lưu bộ từ" }).click();
await page.waitForURL(u => /\/vocabulary\/sets\/vset_/.test(u.pathname));
const setId = page.url().split("/").pop();
await page.goto(base + "/vocabulary/sets/" + setId + "/edit");
await page.locator(".bulk-vocab-editor textarea").waitFor({ state: "visible" });
await page.locator("textarea.input.min-h-28").fill("happy:hạnh phúc\napple:quả táo\nhello:xin chào\nbook:quyển sách\nwater:nước");
await page.getByRole("button", { name: "Thêm nhanh" }).click();
await page.getByText("quyển sách").waitFor();
const dump = async label => {
  const r = await page.evaluate(async sid => {
    const db = await new Promise((res, rej) => { const q = indexedDB.open("exam-platform"); q.onsuccess = () => res(q.result); q.onerror = () => rej(q.error); });
    const count = async (store, fn) => new Promise((res, rej) => { const t = db.transaction(store).objectStore(store); const req = fn(t); req.onsuccess = () => res(req.result); req.onerror = () => rej(req.error); });
    const items = await new Promise((res, rej) => { const t = db.transaction("vocabularySetItems").objectStore("vocabularySetItems"); const out = []; const req = t.index("setId").getAllKeys(sid); req.onsuccess = () => res(req.result); req.onerror = () => rej(req.error); });
    const queue = await count("syncQueue", s => s.count());
    const queueRows = await new Promise((res, rej) => { const t = db.transaction("syncQueue").objectStore("syncQueue"); const out = []; const c = t.openCursor(); c.onsuccess = () => { const cur = c.result; if (cur) { out.push({ et: cur.value.entityType, op: cur.value.operation, st: cur.value.status, e: cur.value.lastError?.slice(0, 80) }); cur.continue(); } else res(out); }; c.onerror = () => rej(c.error); });
    return { items: items.length, queue, queueRows };
  }, setId);
  console.log(label, JSON.stringify(r));
};
await dump("t0 ");
await page.waitForTimeout(2500);
await dump("t2.5");
await page.goto(base + "/vocabulary/sets/" + setId);
await page.locator(".vocab-mode-grid").waitFor();
console.log("stats after reload:", JSON.stringify(await page.locator(".vocab-stat strong").allTextContents()));
await browser.close();
