import { chromium } from "@playwright/test";
const base = "http://127.0.0.1:4173";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 1000 } })).newPage();
const suf = Date.now();
await page.goto(base + "/register");
await page.getByPlaceholder("Tên hiển thị").fill("Probe " + suf);
await page.getByPlaceholder("Username").fill("probe_" + suf);
await page.getByPlaceholder("Mật khẩu (ít nhất 10 ký tự)").fill("shot-password-123");
await page.getByPlaceholder("Nhập lại mật khẩu").fill("shot-password-123");
await page.getByRole("button", { name: "Đăng ký & vào học" }).click();
await page.getByRole("heading", { name: /Kho đề/ }).waitFor();
await page.goto(base + "/vocabulary/sets/new");
await page.getByLabel("Tên", { exact: true }).fill("Probe set " + suf);
await page.getByRole("button", { name: "Lưu bộ từ" }).click();
await page.waitForURL(u => /\/vocabulary\/sets\/vset_/.test(u.pathname));
const setId = page.url().split("/").pop();
console.log("setId:", setId);
await page.goto(base + "/vocabulary/sets/" + setId + "/edit");
await page.locator(".bulk-vocab-editor textarea").waitFor({ state: "visible" });
await page.locator("textarea.input.min-h-28").fill("happy:hạnh phúc\napple:quả táo\nhello:xin chào\nbook:quyển sách\nwater:nước");
await page.getByRole("button", { name: "Thêm nhanh" }).click();
await page.getByText("quyển sách").waitFor();
await page.goto(base + "/vocabulary/sets/" + setId);
await page.locator(".vocab-mode-grid").waitFor();
const stats = await page.locator(".vocab-stat strong").allTextContents();
const cards = await page.locator(".vocab-mode-card").evaluateAll(els => els.map(e => ({ text: e.textContent.slice(0, 24), disabled: e.disabled })));
const h1 = await page.locator("h1").first().textContent();
console.log("h1:", h1);
console.log("stats:", JSON.stringify(stats));
console.log("cards:", JSON.stringify(cards));
await browser.close();
