import { useEffect, useState } from 'react';
import type { Question, QuestionType, TrueFalseStatement } from '../../../domain/exam/exam.types';
import { RichTextEditor } from './RichTextEditor';
import { addQuestionImage } from '../../../domain/exam/exam.asset.service';
import { QuestionImage } from './QuestionImage';

type Props={question:Question;onChange:(q:Question)=>void;onDelete:()=>void;onMove:(delta:number)=>void};
export function QuestionEditor({question,onChange,onDelete,onMove}:Props){const patch=(p:Partial<Question>)=>onChange({...question,...p} as Question);return <div className="card space-y-3"><div className="flex items-center justify-between"><strong>Câu {question.order+1}</strong><div className="flex gap-1"><button type="button" className="btn-secondary" onClick={()=>onMove(-1)}>↑</button><button type="button" className="btn-secondary" onClick={()=>onMove(1)}>↓</button><button type="button" className="text-grade text-sm px-2" onClick={onDelete}>Xóa</button></div></div><select className="input" value={question.type} onChange={e=>onChange(makeType(e.target.value as QuestionType,question))}><option value="ABCD">ABCD</option><option value="TRUE_FALSE">TRUE / FALSE</option><option value="SHORT_ANSWER">SHORT ANSWER</option></select><RichTextEditor value={question.content} onChange={content=>patch({content})} placeholder="Nhập nội dung câu hỏi..."/><div className="question-explanation-editor"><label className="text-sm font-semibold">Giải thích sẵn</label><p className="text-xs muted">Nếu điền, khi người học làm sai hệ thống sẽ dùng giải thích này thay vì gọi AI.</p><textarea className="input min-h-24" value={question.explanation??''} onChange={e=>patch({explanation:e.target.value||undefined})} placeholder="Giải thích vì sao đáp án đúng..." /></div><div className="question-image-editor"><div className="flex items-center justify-between gap-2"><div><div className="text-sm font-semibold">Hình ảnh câu hỏi</div><p className="text-xs muted">Ảnh được lưu trong máy để dùng offline và tự upload ImgBB khi có mạng.</p></div><label className="btn-secondary cursor-pointer"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const asset=await addQuestionImage(question.examId,question.id,file);patch({imageAssetId:asset.id, imageUrl:asset.remoteUrl});}catch(err){alert(err instanceof Error?err.message:'Không thể thêm ảnh');}finally{e.currentTarget.value='';}}}/>{question.imageAssetId?'Đổi ảnh':'Thêm hình ảnh'}</label></div>{question.imageAssetId&&<QuestionImage assetId={question.imageAssetId}/>}</div><input className="input" type="number" min="0.1" step="0.5" value={question.points} onChange={e=>patch({points:Number(e.target.value)})}/>{question.type==='ABCD'&&<ABCDEditor question={question} onChange={onChange}/>} {question.type==='TRUE_FALSE'&&<TrueFalseEditor question={question} onChange={onChange}/>} {question.type==='SHORT_ANSWER'&&<ShortEditor question={question} onChange={onChange}/>}</div>}
function ABCDEditor({question,onChange}:{question:Extract<Question,{type:'ABCD'}>;onChange:(q:Question)=>void}){return <div className="space-y-2">{question.options.map((o,i)=><div className="flex gap-2" key={o.id}><span className="w-6 pt-2">{String.fromCharCode(65+i)}</span><RichTextEditor className="flex-1" value={o.text} onChange={text=>onChange({...question,options:question.options.map(x=>x.id===o.id?{...x,text}:x)})} placeholder={`Lựa chọn ${String.fromCharCode(65+i)}`}/><button type="button" className={question.correctOptionId===o.id?'btn-primary':'btn-secondary'} onClick={()=>onChange({...question,correctOptionId:o.id})}>Đúng</button></div>)}</div>}

function TrueFalseEditor({question,onChange}:{question:Extract<Question,{type:'TRUE_FALSE'}>;onChange:(q:Question)=>void}){
 const statements=question.statements?.length===4?question.statements:[
  {id:`${question.id}_s1`,text:'Mệnh đề 1',correct:true},
  {id:`${question.id}_s2`,text:'Mệnh đề 2',correct:false},
  {id:`${question.id}_s3`,text:'Mệnh đề 3',correct:true},
  {id:`${question.id}_s4`,text:'Mệnh đề 4',correct:false}
 ];
 const update=(next:TrueFalseStatement[])=>onChange({...question,statements:next,correctAnswer:next.every(x=>x.correct)});
 return <div className="tf-editor">
   <div className="text-sm font-semibold">4 mệnh đề Đúng / Sai</div>
   <p className="text-xs muted">Mỗi câu gồm 4 mệnh đề. Khi làm bài, thứ tự mệnh đề sẽ được xáo trộn nhưng đáp án Đúng/Sai đi cùng mệnh đề.</p>
   {statements.map((st,i)=><div className="tf-editor-row" key={st.id}><span className="tf-editor-number">{i+1}</span><input className="input flex-1" value={st.text} onChange={e=>update(statements.map((x,j)=>j===i?{...x,text:e.target.value}:x))}/><button type="button" className={st.correct?'btn-primary':'btn-secondary'} onClick={()=>update(statements.map((x,j)=>j===i?{...x,correct:!x.correct}:x))}>{st.correct?'Đúng':'Sai'}</button></div>)}
 </div>;
}

function ShortEditor({question,onChange}:{question:Extract<Question,{type:'SHORT_ANSWER'}>;onChange:(q:Question)=>void}){const [answers,setAnswers]=useState(question.acceptedAnswers.join('\n'));useEffect(()=>setAnswers(question.acceptedAnswers.join('\n')),[question.id]);return <div className="space-y-2"><label className="text-sm font-medium">Đáp án chuẩn (mỗi dòng một đáp án)</label><textarea className="input min-h-24" value={answers} onChange={e=>{setAnswers(e.target.value);onChange({...question,acceptedAnswers:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}}/></div>}
function makeType(type:QuestionType,q:Question):Question{const base={id:q.id,examId:q.examId,order:q.order,content:q.content,explanation:q.explanation,points:q.points,imageAssetId:q.imageAssetId};if(type==='ABCD')return {...base,type,options:[{id:`${q.id}_a`,text:'Lựa chọn A'},{id:`${q.id}_b`,text:'Lựa chọn B'},{id:`${q.id}_c`,text:'Lựa chọn C'},{id:`${q.id}_d`,text:'Lựa chọn D'}],correctOptionId:`${q.id}_a`};if(type==='TRUE_FALSE')return {...base,type,correctAnswer:true,statements:[{id:`${q.id}_s1`,text:'Mệnh đề 1',correct:true},{id:`${q.id}_s2`,text:'Mệnh đề 2',correct:false},{id:`${q.id}_s3`,text:'Mệnh đề 3',correct:true},{id:`${q.id}_s4`,text:'Mệnh đề 4',correct:false}]};return {...base,type,acceptedAnswers:['Đáp án'],caseSensitive:false};}
