import { useEffect, useState } from 'react';
import type { Question, QuestionType } from '../../../domain/exam/exam.types';
import { RichTextEditor } from './RichTextEditor';

type Props={question:Question;onChange:(q:Question)=>void;onDelete:()=>void;onMove:(delta:number)=>void};
export function QuestionEditor({question,onChange,onDelete,onMove}:Props){const patch=(p:Partial<Question>)=>onChange({...question,...p} as Question);return <div className="card space-y-3"><div className="flex items-center justify-between"><strong>Câu {question.order+1}</strong><div className="flex gap-1"><button type="button" className="btn-secondary" onClick={()=>onMove(-1)}>↑</button><button type="button" className="btn-secondary" onClick={()=>onMove(1)}>↓</button><button type="button" className="text-red-600 text-sm px-2" onClick={onDelete}>Xóa</button></div></div><select className="input" value={question.type} onChange={e=>onChange(makeType(e.target.value as QuestionType,question))}><option value="ABCD">ABCD</option><option value="TRUE_FALSE">TRUE / FALSE</option><option value="SHORT_ANSWER">SHORT ANSWER</option></select><RichTextEditor value={question.content} onChange={content=>patch({content})} placeholder="Nhập nội dung câu hỏi..."/><input className="input" type="number" min="0.1" step="0.5" value={question.points} onChange={e=>patch({points:Number(e.target.value)})}/>{question.type==='ABCD'&&<ABCDEditor question={question} onChange={onChange}/>} {question.type==='TRUE_FALSE'&&<label className="flex gap-2"><input type="checkbox" checked={question.correctAnswer} onChange={e=>onChange({...question,correctAnswer:e.target.checked})}/> Đáp án đúng là ĐÚNG</label>} {question.type==='SHORT_ANSWER'&&<ShortEditor question={question} onChange={onChange}/>}</div>}
function ABCDEditor({question,onChange}:{question:Extract<Question,{type:'ABCD'}>;onChange:(q:Question)=>void}){return <div className="space-y-2">{question.options.map((o,i)=><div className="flex gap-2" key={o.id}><span className="w-6 pt-2">{String.fromCharCode(65+i)}</span><RichTextEditor className="flex-1" value={o.text} onChange={text=>onChange({...question,options:question.options.map(x=>x.id===o.id?{...x,text}:x)})} placeholder={`Lựa chọn ${String.fromCharCode(65+i)}`}/><button type="button" className={question.correctOptionId===o.id?'btn-primary':'btn-secondary'} onClick={()=>onChange({...question,correctOptionId:o.id})}>Đúng</button></div>)}</div>}
function ShortEditor({question,onChange}:{question:Extract<Question,{type:'SHORT_ANSWER'}>;onChange:(q:Question)=>void}){const [answers,setAnswers]=useState(question.acceptedAnswers.join('\n'));useEffect(()=>setAnswers(question.acceptedAnswers.join('\n')),[question.id]);return <div className="space-y-2"><label className="text-sm font-medium">Đáp án chuẩn (mỗi dòng một đáp án)</label><textarea className="input min-h-24" value={answers} onChange={e=>{setAnswers(e.target.value);onChange({...question,acceptedAnswers:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}}/></div>}
function makeType(type:QuestionType,q:Question):Question{const base={id:q.id,examId:q.examId,order:q.order,content:q.content,explanation:q.explanation,points:q.points,imageAssetId:q.imageAssetId};if(type==='ABCD')return {...base,type,options:[{id:`${q.id}_a`,text:'Lựa chọn A'},{id:`${q.id}_b`,text:'Lựa chọn B'},{id:`${q.id}_c`,text:'Lựa chọn C'},{id:`${q.id}_d`,text:'Lựa chọn D'}],correctOptionId:`${q.id}_a`};if(type==='TRUE_FALSE')return {...base,type,correctAnswer:true};return {...base,type,acceptedAnswers:['Đáp án'],caseSensitive:false};}
