import { describe, expect, it } from 'vitest';
import { exportExam, importExam, hashExam, sanitizeFilename } from '@exam/exam-format';
import type { ExamContentInput } from '@exam/schemas';
function baseContent(overrides:any={}):ExamContentInput{return {id:'exam_1',title:'Đề thi thử số 1',description:'Mô tả',subject:'Toán',grade:10,duration:3600,questionCount:3,source:'local',version:1,contentHash:'sha256:'+'0'.repeat(64),createdAt:1700000000000,updatedAt:1700000000000,questions:[{id:'q1',examId:'exam_1',order:0,type:'ABCD',content:'2 + 2 = ?',points:2,options:[{id:'a',text:'3'},{id:'b',text:'4'},{id:'c',text:'5'},{id:'d',text:'6'}],correctOptionId:'b'},{id:'q2',examId:'exam_1',order:1,type:'SHORT_ANSWER',content:'Thủ đô?',points:1,correctAnswers:['Hà Nội','Ha Noi'],caseSensitive:false},{id:'q3',examId:'exam_1',order:2,type:'TRUE_FALSE',content:'Hà Nội là thủ đô.',points:1,correctAnswer:true}],...overrides};}
it('round-trips canonical content and hash',async()=>{const content=baseContent();const zip=await exportExam({content:{...content}});const imported=await importExam(zip);expect(imported.content.questions.map(q=>q.type)).toEqual(['ABCD','SHORT_ANSWER','TRUE_FALSE']);expect(imported.content.questions[1]).toMatchObject({correctAnswers:['Hà Nội','Ha Noi']});expect(imported.contentHash).toBe(imported.manifest.contentHash);expect(await hashExam(imported.content)).toBe(imported.manifest.contentHash);});
it('hash is stable and sensitive to content',async()=>{const a=baseContent();const h=await hashExam(a);expect(await hashExam({...a,title:a.title})).toBe(h);expect(await hashExam({...a,title:'Khác'})).not.toBe(h);expect(await hashExam({...a,duration:7200})).not.toBe(h);});
it('sanitizeFilename is safe',()=>{expect(sanitizeFilename('A/B:C?.exam')).toBe('A-B-C-.exam');});
it('rejects invalid ABCD export content',async()=>{const bad=baseContent({questions:[{id:'q1',examId:'exam_1',order:0,type:'ABCD',content:'x',points:1,options:[{id:'a',text:'A'},{id:'b',text:'B'}],answer:'a'}] as any,questionCount:1});await expect(exportExam({content:{...bad}})).rejects.toThrow();});
it('adapts legacy self-answer exam questions to SHORT_ANSWER',async()=>{const legacy:any=baseContent({questions:[{id:'q1',examId:'exam_1',order:0,type:'text',content:'Tự luận',points:1,answer:'Hà Nội'}],questionCount:1});const { exportExam: exportCurrent }=await import('@exam/exam-format');void exportCurrent;const rawHash=await hashExam(legacy);const JSZip=(await import('jszip')).default;const zip=new JSZip();zip.file('manifest.json',JSON.stringify({format:'exam',formatVersion:1,examId:legacy.id,title:legacy.title,version:legacy.version,createdAt:new Date(legacy.createdAt).toISOString(),updatedAt:new Date(legacy.updatedAt).toISOString(),contentHash:rawHash,questionCount:1,assets:[]}));zip.file('exam.json',JSON.stringify({...legacy,contentHash:rawHash}));const imported=await importExam(await zip.generateAsync({type:'uint8array'}));expect(imported.content.questions[0].type).toBe('SHORT_ANSWER');expect(imported.content.questions[0]).toMatchObject({correctAnswers:['Hà Nội']});});
it('reports the schema path for invalid exam content',async()=>{const bad=baseContent({questions:[{id:'q1',examId:'exam_1',order:0,type:'ABCD',content:'x',points:1,options:[],correctOptionId:'missing'}] as any,questionCount:1});await expect(exportExam({content:{...bad}})).rejects.toThrow(/questions\.0/);});

it('accepts canonical directory entries emitted by JSZip for asset folders',async()=>{const JSZip=(await import('jszip')).default;const content=baseContent({questionCount:1,questions:[{id:'q1',examId:'exam_1',order:0,type:'ABCD',content:'x',points:1,options:[{id:'a',text:'A'},{id:'b',text:'B'},{id:'c',text:'C'},{id:'d',text:'D'}],correctOptionId:'a'}] as any});const hash=await hashExam(content);const zip=new JSZip();zip.file('manifest.json',JSON.stringify({format:'exam',formatVersion:1,examId:content.id,title:content.title,version:content.version,createdAt:new Date(content.createdAt).toISOString(),updatedAt:new Date(content.updatedAt).toISOString(),contentHash:hash,questionCount:1,assets:[]}));zip.file('exam.json',JSON.stringify({...content,contentHash:hash}));zip.folder('assets');await expect(importExam(await zip.generateAsync({type:'uint8array'}))).resolves.toBeTruthy();});
