import { describe, expect, it } from 'vitest';
import { ExamDraftSchema } from '@exam/schemas';
import { isAnswerCorrect, normalizeText } from '../domain/exam/answer.scoring';
import { validateQuestion } from '../domain/exam/question.service';
import type { Question } from '../domain/exam/exam.types';
const abcd:Question={id:'q1',examId:'e',order:0,type:'ABCD',content:'Capital?',points:1,options:[{id:'paris',text:'Paris'},{id:'london',text:'London'},{id:'tokyo',text:'Tokyo'},{id:'rome',text:'Rome'}],correctOptionId:'paris'};
const tf:Question={id:'q2',examId:'e',order:1,type:'TRUE_FALSE',content:'x',points:1,correctAnswer:true};
const sa:Question={id:'q3',examId:'e',order:2,type:'SHORT_ANSWER',content:'x',points:1,acceptedAnswers:['Hà Nội','Ha Noi']};
describe('exam JSON and scoring rules',()=>{it('accepts valid JSON shape',()=>{expect(ExamDraftSchema.safeParse({title:'T',subject:'S',questions:[{id:'q1',type:'ABCD',content:'x',options:[{id:'a',text:'A'},{id:'b',text:'B'},{id:'c',text:'C'},{id:'d',text:'D'}],correctOptionId:'a'},{id:'q2',type:'TRUE_FALSE',content:'x',correctAnswer:true},{id:'q3',type:'SHORT_ANSWER',content:'x',correctAnswers:['A']}]}).success).toBe(true);});it('rejects invalid question type and wrong ABCD option count',()=>{expect(ExamDraftSchema.safeParse({title:'T',subject:'S',questions:[{id:'q1',type:'MATCHING',content:'x'}]}).success).toBe(false);expect(ExamDraftSchema.safeParse({title:'T',subject:'S',questions:[{id:'q1',type:'ABCD',content:'x',options:[{id:'a',text:'A'}],correctOptionId:'a'}]}).success).toBe(false);});it('rejects invalid correctOptionId semantically',()=>{const q={id:'q1',type:'ABCD',content:'x',options:[{id:'a',text:'A'},{id:'b',text:'B'},{id:'c',text:'C'},{id:'d',text:'D'}],correctOptionId:'x'};expect(ExamDraftSchema.safeParse({title:'T',subject:'S',questions:[q]}).success).toBe(true);expect(()=>validateQuestion({...q,points:1,examId:'e',order:0} as any)).toThrow();});it('normalizes Unicode NFC, case and whitespace while keeping accents',()=>{expect(normalizeText('  HÀ  NỘI  ')).toBe('hà nội');expect(normalizeText('e\u0301')).toBe('é');});it('scores stable IDs, true/false and accepted short answers',()=>{expect(isAnswerCorrect(abcd,{type:'ABCD',selectedOptionId:'paris'})).toBe(true);expect(isAnswerCorrect(abcd,{type:'ABCD',selectedOptionId:'london'})).toBe(false);expect(isAnswerCorrect(tf,{type:'TRUE_FALSE',selectedAnswer:true})).toBe(true);expect(isAnswerCorrect(tf,{type:'TRUE_FALSE',selectedAnswer:false})).toBe(false);expect(isAnswerCorrect(sa,{type:'SHORT_ANSWER',text:'  hà   nội '})).toBe(true);});});
