import { beforeEach, describe, expect, it } from 'vitest';
import 'fake-indexeddb/auto';
import { db } from '../db/database';
import { vocabularyService } from '../domain/vocabulary/vocabulary.service';
import { vocabularySetService } from '../domain/vocabulary/vocabulary.set.service';
import { selectSmartQuestions } from '../domain/vocabulary/vocabulary.smart-selection';
import { vocabularySetSessionService } from '../domain/vocabulary/vocabulary.set.session.service';
import type { VocabProgress, VocabQuestion, Vocabulary } from '@exam/shared-types';

beforeEach(async()=>{await db.vocabSessionAnswers.clear();await db.vocabSessions.clear();await db.vocabularySetItems.clear();await db.vocabularySets.clear();await db.vocabProgress.clear();await db.vocabQuestions.clear();await db.vocabularies.clear();});
const now=1_000;
async function makeWords(){const a=await vocabularyService.create('p1',{english:'Apple',vietnamese:'quả táo'},now);const b=await vocabularyService.create('p1',{english:'Book',vietnamese:'quyển sách'},now+1);const c=await vocabularyService.create('p1',{english:'Cat',vietnamese:'con mèo'},now+2);const d=await vocabularyService.create('p1',{english:'Sun',vietnamese:'mặt trời'},now+3);return [a,b,c,d];}

describe('vocabulary sets',()=>{
 it('creates, adds, removes and reorders words without duplicating vocabulary',async()=>{const [a,b,c]=await makeWords();const s=await vocabularySetService.create('p1',{name:'Basics'},10);await vocabularySetService.addVocabulary('p1',s.id,a.id,11);await vocabularySetService.addVocabulary('p1',s.id,b.id,12);await vocabularySetService.addVocabulary('p1',s.id,c.id,13);await vocabularySetService.reorderVocabulary('p1',s.id,[c.id,a.id,b.id],14);const d=await vocabularySetService.detail('p1',s.id);expect(d.vocabularies.map(x=>x.id)).toEqual([c.id,a.id,b.id]);expect(d.set.wordCount).toBe(3);await vocabularySetService.removeVocabulary('p1',s.id,a.id,15);expect((await vocabularySetService.detail('p1',s.id)).set.wordCount).toBe(2);await vocabularySetService.delete('p1',s.id,16);expect(await vocabularyService.get('p1',b.id)).toBeDefined();});
 it('isolates profiles and safely ignores a deleted vocabulary',async()=>{const [a]=await makeWords();const s=await vocabularySetService.create('p1',{name:'A'},1);await vocabularySetService.addVocabulary('p1',s.id,a.id,2);await expect(vocabularySetService.get('p2',s.id)).rejects.toThrow();await expect(vocabularySetService.update('p2',s.id,{name:'Hacked'})).rejects.toThrow();await expect(vocabularySetService.delete('p2',s.id)).rejects.toThrow();await vocabularyService.delete('p1',a.id);const d=await vocabularySetService.detail('p1',s.id);expect(d.vocabularies).toHaveLength(0);await expect(vocabularySetService.addVocabulary('p2',s.id,a.id)).rejects.toThrow();});
});

function question(id:string,vocabularyId:string,type:any):VocabQuestion{return {id,vocabularyId,profileId:'p1',type,prompt:'x',answer:'x',availability:'available',generatorVersion:1,vocabularyGeneration:1,createdAt:1,updatedAt:1};}
function progress(vocabularyId:string,type:any,mastery:number,attemptCount=1,wrongCount=0):VocabProgress{return {id:`${vocabularyId}:${type}`,vocabularyId,profileId:'p1',questionType:type,vocabularyGeneration:1,correctCount:attemptCount-wrongCount,wrongCount,attemptCount,currentStreak:0,bestStreak:1,mastery};}
describe('smart selection',()=>{
 it('filters all/weak/wrong/new/custom, excludes unavailable and is deterministic',()=>{const qs=[question('a1','a','TEXT_EN_TO_VI'),question('a2','a','LETTER_ORDER'),question('b1','b','TEXT_EN_TO_VI'),{...question('c1','c','TEXT_EN_TO_VI'),availability:'unavailable' as const}];const ps=[progress('a','TEXT_EN_TO_VI',20,5,2),progress('b','TEXT_EN_TO_VI',90,5,0)];const base={questions:qs,progress:ps,questionTypes:['TEXT_EN_TO_VI','LETTER_ORDER'] as any,seed:'seed'};expect(selectSmartQuestions({...base,mode:'ALL',requestedCount:'all'}).some(q=>q.id==='c1')).toBe(false);expect(selectSmartQuestions({...base,mode:'WEAK',requestedCount:1})[0].vocabularyId).toBe('a');expect(selectSmartQuestions({...base,mode:'WRONG',requestedCount:'all',wrongQuestionIds:new Set(['a1'])}).map(q=>q.id)).toEqual(['a1']);expect(selectSmartQuestions({...base,mode:'NEW',requestedCount:'all',attemptedQuestionIds:new Set(['a1','a2'])}).map(q=>q.id)).toEqual(['b1']);const one=selectSmartQuestions({...base,mode:'CUSTOM',requestedCount:2});expect(one).toEqual(selectSmartQuestions({...base,mode:'CUSTOM',requestedCount:2}));});
});

describe('set session recovery',()=>{
 it('persists selected filters/order/index/answers and result',async()=>{const [a,b,c,d]=await makeWords();const s=await vocabularySetService.create('p1',{name:'Basics'},10);for(const v of [a,b,c,d])await vocabularySetService.addVocabulary('p1',s.id,v.id,11);const state=await vocabularySetSessionService.create('p1',s.id,{mode:'CUSTOM',requestedCount:5,questionTypes:['TEXT_EN_TO_VI','LETTER_ORDER'],seed:'fixed',startedAt:0});expect(state.session.selectedQuestionTypes).toEqual(['TEXT_EN_TO_VI','LETTER_ORDER']);expect(state.session.questionIds).toEqual(state.session.selectedQuestionIds);const q=state.questions[0];await vocabularySetSessionService.answer('p1',state.session.id,q.answer,5000);await vocabularySetSessionService.next('p1',state.session.id,7000);const resumed=await vocabularySetSessionService.resume('p1',s.id);expect(resumed?.currentQuestionIndex).toBe(1);expect(resumed?.session.seed).toBe('fixed');expect(resumed?.answers[q.id]).toBe(q.answer);const result=await vocabularySetSessionService.submit('p1',state.session.id,9000);expect(result.correct).toBe(1);expect(result.unanswered).toBe(state.questions.length-1);expect(result.timeSpent).toBe(5);await vocabularySetService.delete('p1',s.id,10000);const historical=await vocabularySetSessionService.result('p1',state.session.id);expect(historical.correct).toBe(1);});
 it('rejects terminal mutations',async()=>{const [a]=await makeWords();const s=await vocabularySetService.create('p1',{name:'One'},1);await vocabularySetService.addVocabulary('p1',s.id,a.id,2);const state=await vocabularySetSessionService.create('p1',s.id,{mode:'ALL',requestedCount:'all',questionTypes:['TEXT_EN_TO_VI'],startedAt:0});await vocabularySetSessionService.submit('p1',state.session.id,10);await expect(vocabularySetSessionService.answer('p1',state.session.id,'x',11)).rejects.toThrow();await expect(vocabularySetSessionService.next('p1',state.session.id)).rejects.toThrow();await expect(vocabularySetSessionService.flag('p1',state.session.id)).rejects.toThrow();});
});

describe('bulk vocabulary import',()=>{
 it('creates unique words once and adds them to the requested set',async()=>{const s=await vocabularySetService.create('p1',{name:'Bulk'},1);const r=await vocabularySetService.addBulkVocabulary('p1',s.id,[{english:'Apple',vietnamese:'quả táo'},{english:' apple ',vietnamese:'quả táo'},{english:'Book',vietnamese:'quyển sách'}],2);expect(r.requested).toBe(2);expect(r.added).toBe(2);expect((await vocabularySetService.detail('p1',s.id)).vocabularies.map(v=>v.english)).toHaveLength(2);});
});
